# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 14:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('AlbumID', models.IntegerField(primary_key=True, serialize=False)),
                ('AlbumName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('ArtistID', models.IntegerField(primary_key=True, serialize=False)),
                ('ArtistName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BelongTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlbumID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
            ],
        ),
        migrations.CreateModel(
            name='CommentOn',
            fields=[
                ('CommentID', models.IntegerField(primary_key=True, serialize=False)),
                ('CommentContent', models.TextField()),
                ('CommentTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('PlayListID', models.IntegerField(primary_key=True, serialize=False)),
                ('PlayListName', models.CharField(max_length=100)),
                ('CreatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlbumID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
                ('ArtistID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('SongID', models.IntegerField(primary_key=True, serialize=False)),
                ('SongName', models.CharField(max_length=100)),
                ('SongLyrics', models.TextField(blank=True)),
                ('SongLink', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='commenton',
            name='SongID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Song'),
        ),
        migrations.AddField(
            model_name='commenton',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='belongto',
            name='SongID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Song'),
        ),
        migrations.AddField(
            model_name='addto',
            name='PlayListID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.PlayList'),
        ),
        migrations.AddField(
            model_name='addto',
            name='SongID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Song'),
        ),
        migrations.AlterUniqueTogether(
            name='release',
            unique_together=set([('ArtistID', 'AlbumID')]),
        ),
        migrations.AlterUniqueTogether(
            name='belongto',
            unique_together=set([('AlbumID', 'SongID')]),
        ),
        migrations.AlterUniqueTogether(
            name='addto',
            unique_together=set([('SongID', 'PlayListID')]),
        ),
    ]
